joint_names: ["rig1_plate_joint", "rig2_plate_joint"]
action_name: /rig12/joint_trajectory_controller/follow_joint_trajectory
service_ns: /rig12/driver
default_vel: 0.3

home: [[0.0, 0.0]]
up: [[0.0, 0.0]]
right: [[-1.5708, -1.5708]]
down: [[3.14, 3.14]]
left: [[1.5708, 1.5708]]
roundtrip: [down,left,up,right]
ticktack: [left,right,left,right]
